# Generated by Django 3.1.7 on 2021-03-06 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('mail', models.EmailField(max_length=254)),
                ('text', models.TextField(max_length=3000)),
                ('time_start', models.DateTimeField(auto_now_add=True)),
                ('time_edit', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='active', max_length=200)),
            ],
            options={
                'verbose_name': 'Регистрация',
                'verbose_name_plural': 'Регистрации',
                'db_table': 'Hotel',
            },
        ),
    ]
